export const GET_ALL_LAYOUT_3 = {
  data: [
    {
      __typename: "Film",
      id: "ZmlsbXM6MQ==",
      title: "A New Hope",
      director: "George Lucas",
      producers: ["Gary Kurtz", "Rick McCallum"],
      releaseDate: "1977-05-25",
    },
    {
      __typename: "Film",
      id: "ZmlsbXM6Mg==",
      title: "The Empire Strikes Back",
      director: "Irvin Kershner",
      producers: ["Gary Kurtz", "Rick McCallum"],
      releaseDate: "1980-05-17",
    },
    {
      __typename: "Film",
      id: "ZmlsbXM6Mw==",
      title: "Return of the Jedi",
      director: "Richard Marquand",
      producers: ["Howard G. Kazanjian", "George Lucas", "Rick McCallum"],
      releaseDate: "1983-05-25",
    },
    {
      __typename: "Film",
      id: "ZmlsbXM6NA==",
      title: "The Phantom Menace",
      director: "George Lucas",
      producers: ["Rick McCallum"],
      releaseDate: "1999-05-19",
    },
    {
      __typename: "Film",
      id: "ZmlsbXM6NQ==",
      title: "Attack of the Clones",
      director: "George Lucas",
      producers: ["Rick McCallum"],
      releaseDate: "2002-05-16",
    },
    {
      __typename: "Film",
      id: "ZmlsbXM6Ng==",
      title: "Revenge of the Sith",
      director: "George Lucas",
      producers: ["Rick McCallum"],
      releaseDate: "2005-05-19",
    },
  ],
  totalCount: 6,
  titleKey: "title",
  title: "Films",
};

export const GET_ALL_LAYOUT_5 = {
  data: [
    {
      __typename: "Person",
      id: "cGVvcGxlOjE=",
      name: "Luke Skywalker",
      birthYear: "19BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "blond",
      height: 172,
      mass: 77,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjI=",
      name: "C-3PO",
      birthYear: "112BBY",
      eyeColor: "yellow",
      gender: "n/a",
      hairColor: "n/a",
      height: 167,
      mass: 75,
      skinColor: "gold",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjM=",
      name: "R2-D2",
      birthYear: "33BBY",
      eyeColor: "red",
      gender: "n/a",
      hairColor: "n/a",
      height: 96,
      mass: 32,
      skinColor: "white, blue",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQ=",
      name: "Darth Vader",
      birthYear: "41.9BBY",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "none",
      height: 202,
      mass: 136,
      skinColor: "white",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjU=",
      name: "Leia Organa",
      birthYear: "19BBY",
      eyeColor: "brown",
      gender: "female",
      hairColor: "brown",
      height: 150,
      mass: 49,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjY=",
      name: "Owen Lars",
      birthYear: "52BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "brown, grey",
      height: 178,
      mass: 120,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjc=",
      name: "Beru Whitesun lars",
      birthYear: "47BBY",
      eyeColor: "blue",
      gender: "female",
      hairColor: "brown",
      height: 165,
      mass: 75,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjg=",
      name: "R5-D4",
      birthYear: "unknown",
      eyeColor: "red",
      gender: "n/a",
      hairColor: "n/a",
      height: 97,
      mass: 32,
      skinColor: "white, red",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjk=",
      name: "Biggs Darklighter",
      birthYear: "24BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 183,
      mass: 84,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjEw",
      name: "Obi-Wan Kenobi",
      birthYear: "57BBY",
      eyeColor: "blue-gray",
      gender: "male",
      hairColor: "auburn, white",
      height: 182,
      mass: 77,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjEx",
      name: "Anakin Skywalker",
      birthYear: "41.9BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "blond",
      height: 188,
      mass: 84,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjEy",
      name: "Wilhuff Tarkin",
      birthYear: "64BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "auburn, grey",
      height: 180,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjEz",
      name: "Chewbacca",
      birthYear: "200BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "brown",
      height: 228,
      mass: 112,
      skinColor: "unknown",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjE0",
      name: "Han Solo",
      birthYear: "29BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "brown",
      height: 180,
      mass: 80,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjE1",
      name: "Greedo",
      birthYear: "44BBY",
      eyeColor: "black",
      gender: "male",
      hairColor: "n/a",
      height: 173,
      mass: 74,
      skinColor: "green",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjE2",
      name: "Jabba Desilijic Tiure",
      birthYear: "600BBY",
      eyeColor: "orange",
      gender: "hermaphrodite",
      hairColor: "n/a",
      height: 175,
      mass: 1358,
      skinColor: "green-tan, brown",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjE4",
      name: "Wedge Antilles",
      birthYear: "21BBY",
      eyeColor: "hazel",
      gender: "male",
      hairColor: "brown",
      height: 170,
      mass: 77,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjE5",
      name: "Jek Tono Porkins",
      birthYear: "unknown",
      eyeColor: "blue",
      gender: "male",
      hairColor: "brown",
      height: 180,
      mass: 110,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjIw",
      name: "Yoda",
      birthYear: "896BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "white",
      height: 66,
      mass: 17,
      skinColor: "green",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjIx",
      name: "Palpatine",
      birthYear: "82BBY",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "grey",
      height: 170,
      mass: 75,
      skinColor: "pale",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjIy",
      name: "Boba Fett",
      birthYear: "31.5BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 183,
      mass: 78.2,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjIz",
      name: "IG-88",
      birthYear: "15BBY",
      eyeColor: "red",
      gender: "none",
      hairColor: "none",
      height: 200,
      mass: 140,
      skinColor: "metal",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjI0",
      name: "Bossk",
      birthYear: "53BBY",
      eyeColor: "red",
      gender: "male",
      hairColor: "none",
      height: 190,
      mass: 113,
      skinColor: "green",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjI1",
      name: "Lando Calrissian",
      birthYear: "31BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 177,
      mass: 79,
      skinColor: "dark",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjI2",
      name: "Lobot",
      birthYear: "37BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "none",
      height: 175,
      mass: 79,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjI3",
      name: "Ackbar",
      birthYear: "41BBY",
      eyeColor: "orange",
      gender: "male",
      hairColor: "none",
      height: 180,
      mass: 83,
      skinColor: "brown mottle",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjI4",
      name: "Mon Mothma",
      birthYear: "48BBY",
      eyeColor: "blue",
      gender: "female",
      hairColor: "auburn",
      height: 150,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjI5",
      name: "Arvel Crynyd",
      birthYear: "unknown",
      eyeColor: "brown",
      gender: "male",
      hairColor: "brown",
      height: null,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjMw",
      name: "Wicket Systri Warrick",
      birthYear: "8BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "brown",
      height: 88,
      mass: 20,
      skinColor: "brown",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjMx",
      name: "Nien Nunb",
      birthYear: "unknown",
      eyeColor: "black",
      gender: "male",
      hairColor: "none",
      height: 160,
      mass: 68,
      skinColor: "grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjMy",
      name: "Qui-Gon Jinn",
      birthYear: "92BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "brown",
      height: 193,
      mass: 89,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjMz",
      name: "Nute Gunray",
      birthYear: "unknown",
      eyeColor: "red",
      gender: "male",
      hairColor: "none",
      height: 191,
      mass: 90,
      skinColor: "mottled green",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjM0",
      name: "Finis Valorum",
      birthYear: "91BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "blond",
      height: 170,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjM1",
      name: "Padmé Amidala",
      birthYear: "46BBY",
      eyeColor: "brown",
      gender: "female",
      hairColor: "brown",
      height: 185,
      mass: 45,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjM2",
      name: "Jar Jar Binks",
      birthYear: "52BBY",
      eyeColor: "orange",
      gender: "male",
      hairColor: "none",
      height: 196,
      mass: 66,
      skinColor: "orange",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjM3",
      name: "Roos Tarpals",
      birthYear: "unknown",
      eyeColor: "orange",
      gender: "male",
      hairColor: "none",
      height: 224,
      mass: 82,
      skinColor: "grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjM4",
      name: "Rugor Nass",
      birthYear: "unknown",
      eyeColor: "orange",
      gender: "male",
      hairColor: "none",
      height: 206,
      mass: null,
      skinColor: "green",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjM5",
      name: "Ric Olié",
      birthYear: "unknown",
      eyeColor: "blue",
      gender: "male",
      hairColor: "brown",
      height: 183,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQw",
      name: "Watto",
      birthYear: "unknown",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "black",
      height: 137,
      mass: null,
      skinColor: "blue, grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQx",
      name: "Sebulba",
      birthYear: "unknown",
      eyeColor: "orange",
      gender: "male",
      hairColor: "none",
      height: 112,
      mass: 40,
      skinColor: "grey, red",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQy",
      name: "Quarsh Panaka",
      birthYear: "62BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 183,
      mass: null,
      skinColor: "dark",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQz",
      name: "Shmi Skywalker",
      birthYear: "72BBY",
      eyeColor: "brown",
      gender: "female",
      hairColor: "black",
      height: 163,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQ0",
      name: "Darth Maul",
      birthYear: "54BBY",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "none",
      height: 175,
      mass: 80,
      skinColor: "red",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQ1",
      name: "Bib Fortuna",
      birthYear: "unknown",
      eyeColor: "pink",
      gender: "male",
      hairColor: "none",
      height: 180,
      mass: null,
      skinColor: "pale",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQ2",
      name: "Ayla Secura",
      birthYear: "48BBY",
      eyeColor: "hazel",
      gender: "female",
      hairColor: "none",
      height: 178,
      mass: 55,
      skinColor: "blue",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQ3",
      name: "Ratts Tyerel",
      birthYear: "unknown",
      eyeColor: "unknown",
      gender: "male",
      hairColor: "none",
      height: 79,
      mass: 15,
      skinColor: "grey, blue",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQ4",
      name: "Dud Bolt",
      birthYear: "unknown",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "none",
      height: 94,
      mass: 45,
      skinColor: "blue, grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjQ5",
      name: "Gasgano",
      birthYear: "unknown",
      eyeColor: "black",
      gender: "male",
      hairColor: "none",
      height: 122,
      mass: null,
      skinColor: "white, blue",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjUw",
      name: "Ben Quadinaros",
      birthYear: "unknown",
      eyeColor: "orange",
      gender: "male",
      hairColor: "none",
      height: 163,
      mass: 65,
      skinColor: "grey, green, yellow",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjUx",
      name: "Mace Windu",
      birthYear: "72BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "none",
      height: 188,
      mass: 84,
      skinColor: "dark",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjUy",
      name: "Ki-Adi-Mundi",
      birthYear: "92BBY",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "white",
      height: 198,
      mass: 82,
      skinColor: "pale",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjUz",
      name: "Kit Fisto",
      birthYear: "unknown",
      eyeColor: "black",
      gender: "male",
      hairColor: "none",
      height: 196,
      mass: 87,
      skinColor: "green",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjU0",
      name: "Eeth Koth",
      birthYear: "unknown",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 171,
      mass: null,
      skinColor: "brown",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjU1",
      name: "Adi Gallia",
      birthYear: "unknown",
      eyeColor: "blue",
      gender: "female",
      hairColor: "none",
      height: 184,
      mass: 50,
      skinColor: "dark",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjU2",
      name: "Saesee Tiin",
      birthYear: "unknown",
      eyeColor: "orange",
      gender: "male",
      hairColor: "none",
      height: 188,
      mass: null,
      skinColor: "pale",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjU3",
      name: "Yarael Poof",
      birthYear: "unknown",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "none",
      height: 264,
      mass: null,
      skinColor: "white",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjU4",
      name: "Plo Koon",
      birthYear: "22BBY",
      eyeColor: "black",
      gender: "male",
      hairColor: "none",
      height: 188,
      mass: 80,
      skinColor: "orange",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjU5",
      name: "Mas Amedda",
      birthYear: "unknown",
      eyeColor: "blue",
      gender: "male",
      hairColor: "none",
      height: 196,
      mass: null,
      skinColor: "blue",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjYw",
      name: "Gregar Typho",
      birthYear: "unknown",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 185,
      mass: 85,
      skinColor: "dark",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjYx",
      name: "Cordé",
      birthYear: "unknown",
      eyeColor: "brown",
      gender: "female",
      hairColor: "brown",
      height: 157,
      mass: null,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjYy",
      name: "Cliegg Lars",
      birthYear: "82BBY",
      eyeColor: "blue",
      gender: "male",
      hairColor: "brown",
      height: 183,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjYz",
      name: "Poggle the Lesser",
      birthYear: "unknown",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "none",
      height: 183,
      mass: 80,
      skinColor: "green",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjY0",
      name: "Luminara Unduli",
      birthYear: "58BBY",
      eyeColor: "blue",
      gender: "female",
      hairColor: "black",
      height: 170,
      mass: 56.2,
      skinColor: "yellow",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjY1",
      name: "Barriss Offee",
      birthYear: "40BBY",
      eyeColor: "blue",
      gender: "female",
      hairColor: "black",
      height: 166,
      mass: 50,
      skinColor: "yellow",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjY2",
      name: "Dormé",
      birthYear: "unknown",
      eyeColor: "brown",
      gender: "female",
      hairColor: "brown",
      height: 165,
      mass: null,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjY3",
      name: "Dooku",
      birthYear: "102BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "white",
      height: 193,
      mass: 80,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjY4",
      name: "Bail Prestor Organa",
      birthYear: "67BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 191,
      mass: null,
      skinColor: "tan",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjY5",
      name: "Jango Fett",
      birthYear: "66BBY",
      eyeColor: "brown",
      gender: "male",
      hairColor: "black",
      height: 183,
      mass: 79,
      skinColor: "tan",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjcw",
      name: "Zam Wesell",
      birthYear: "unknown",
      eyeColor: "yellow",
      gender: "female",
      hairColor: "blonde",
      height: 168,
      mass: 55,
      skinColor: "fair, green, yellow",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjcx",
      name: "Dexter Jettster",
      birthYear: "unknown",
      eyeColor: "yellow",
      gender: "male",
      hairColor: "none",
      height: 198,
      mass: 102,
      skinColor: "brown",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjcy",
      name: "Lama Su",
      birthYear: "unknown",
      eyeColor: "black",
      gender: "male",
      hairColor: "none",
      height: 229,
      mass: 88,
      skinColor: "grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjcz",
      name: "Taun We",
      birthYear: "unknown",
      eyeColor: "black",
      gender: "female",
      hairColor: "none",
      height: 213,
      mass: null,
      skinColor: "grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjc0",
      name: "Jocasta Nu",
      birthYear: "unknown",
      eyeColor: "blue",
      gender: "female",
      hairColor: "white",
      height: 167,
      mass: null,
      skinColor: "fair",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjc1",
      name: "R4-P17",
      birthYear: "unknown",
      eyeColor: "red, blue",
      gender: "female",
      hairColor: "none",
      height: 96,
      mass: null,
      skinColor: "silver, red",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjc2",
      name: "Wat Tambor",
      birthYear: "unknown",
      eyeColor: "unknown",
      gender: "male",
      hairColor: "none",
      height: 193,
      mass: 48,
      skinColor: "green, grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjc3",
      name: "San Hill",
      birthYear: "unknown",
      eyeColor: "gold",
      gender: "male",
      hairColor: "none",
      height: 191,
      mass: null,
      skinColor: "grey",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjc4",
      name: "Shaak Ti",
      birthYear: "unknown",
      eyeColor: "black",
      gender: "female",
      hairColor: "none",
      height: 178,
      mass: 57,
      skinColor: "red, blue, white",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjc5",
      name: "Grievous",
      birthYear: "unknown",
      eyeColor: "green, yellow",
      gender: "male",
      hairColor: "none",
      height: 216,
      mass: 159,
      skinColor: "brown, white",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjgw",
      name: "Tarfful",
      birthYear: "unknown",
      eyeColor: "blue",
      gender: "male",
      hairColor: "brown",
      height: 234,
      mass: 136,
      skinColor: "brown",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjgx",
      name: "Raymus Antilles",
      birthYear: "unknown",
      eyeColor: "brown",
      gender: "male",
      hairColor: "brown",
      height: 188,
      mass: 79,
      skinColor: "light",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjgy",
      name: "Sly Moore",
      birthYear: "unknown",
      eyeColor: "white",
      gender: "female",
      hairColor: "none",
      height: 178,
      mass: 48,
      skinColor: "pale",
    },
    {
      __typename: "Person",
      id: "cGVvcGxlOjgz",
      name: "Tion Medon",
      birthYear: "unknown",
      eyeColor: "black",
      gender: "male",
      hairColor: "none",
      height: 206,
      mass: 80,
      skinColor: "grey",
    },
  ],
  totalCount: 82,
  title: "Characters",
};

export const GET_ALL_LAYOUT_4 = {
  data: [
    {
      __typename: "Species",
      id: "c3BlY2llczox",
      name: "Human",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: 120,
      eyeColors: ["brown", "blue", "green", "hazel", "grey", "amber"],
      hairColors: ["blonde", "brown", "black", "red"],
      skinColors: ["caucasian", "black", "asian", "hispanic"],
      language: "Galactic Basic",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoy",
      name: "Droid",
      classification: "artificial",
      designation: "sentient",
      averageHeight: null,
      averageLifespan: null,
      eyeColors: ["n/a"],
      hairColors: ["n/a"],
      skinColors: ["n/a"],
      language: "n/a",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoz",
      name: "Wookie",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 210,
      averageLifespan: 400,
      eyeColors: ["blue", "green", "yellow", "brown", "golden", "red"],
      hairColors: ["black", "brown"],
      skinColors: ["gray"],
      language: "Shyriiwook",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczo0",
      name: "Rodian",
      classification: "sentient",
      designation: "reptilian",
      averageHeight: 170,
      averageLifespan: null,
      eyeColors: ["black"],
      hairColors: ["n/a"],
      skinColors: ["green", "blue"],
      language: "Galatic Basic",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczo1",
      name: "Hutt",
      classification: "gastropod",
      designation: "sentient",
      averageHeight: 300,
      averageLifespan: 1000,
      eyeColors: ["yellow", "red"],
      hairColors: ["n/a"],
      skinColors: ["green", "brown", "tan"],
      language: "Huttese",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczo2",
      name: "Yoda's species",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 66,
      averageLifespan: 900,
      eyeColors: ["brown", "green", "yellow"],
      hairColors: ["brown", "white"],
      skinColors: ["green", "yellow"],
      language: "Galactic basic",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczo3",
      name: "Trandoshan",
      classification: "reptile",
      designation: "sentient",
      averageHeight: 200,
      averageLifespan: null,
      eyeColors: ["yellow", "orange"],
      hairColors: [],
      skinColors: ["brown", "green"],
      language: "Dosh",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczo4",
      name: "Mon Calamari",
      classification: "amphibian",
      designation: "sentient",
      averageHeight: 160,
      averageLifespan: null,
      eyeColors: ["yellow"],
      hairColors: [],
      skinColors: ["red", "blue", "brown", "magenta"],
      language: "Mon Calamarian",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczo5",
      name: "Ewok",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 100,
      averageLifespan: null,
      eyeColors: ["orange", "brown"],
      hairColors: ["white", "brown", "black"],
      skinColors: ["brown"],
      language: "Ewokese",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxMA==",
      name: "Sullustan",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: null,
      eyeColors: ["black"],
      hairColors: [],
      skinColors: ["pale"],
      language: "Sullutese",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxMQ==",
      name: "Neimodian",
      classification: "unknown",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: null,
      eyeColors: ["red", "pink"],
      hairColors: [],
      skinColors: ["grey", "green"],
      language: "Neimoidia",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxMg==",
      name: "Gungan",
      classification: "amphibian",
      designation: "sentient",
      averageHeight: 190,
      averageLifespan: null,
      eyeColors: ["orange"],
      hairColors: [],
      skinColors: ["brown", "green"],
      language: "Gungan basic",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxMw==",
      name: "Toydarian",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 120,
      averageLifespan: 91,
      eyeColors: ["yellow"],
      hairColors: [],
      skinColors: ["blue", "green", "grey"],
      language: "Toydarian",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxNA==",
      name: "Dug",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 100,
      averageLifespan: null,
      eyeColors: ["yellow", "blue"],
      hairColors: [],
      skinColors: ["brown", "purple", "grey", "red"],
      language: "Dugese",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxNQ==",
      name: "Twi'lek",
      classification: "mammals",
      designation: "sentient",
      averageHeight: 200,
      averageLifespan: null,
      eyeColors: ["blue", "brown", "orange", "pink"],
      hairColors: [],
      skinColors: [
        "orange",
        "yellow",
        "blue",
        "green",
        "pink",
        "purple",
        "tan",
      ],
      language: "Twi'leki",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxNg==",
      name: "Aleena",
      classification: "reptile",
      designation: "sentient",
      averageHeight: 80,
      averageLifespan: 79,
      eyeColors: ["unknown"],
      hairColors: [],
      skinColors: ["blue", "gray"],
      language: "Aleena",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxNw==",
      name: "Vulptereen",
      classification: "unknown",
      designation: "sentient",
      averageHeight: 100,
      averageLifespan: null,
      eyeColors: ["yellow"],
      hairColors: [],
      skinColors: ["grey"],
      language: "vulpterish",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxOA==",
      name: "Xexto",
      classification: "unknown",
      designation: "sentient",
      averageHeight: 125,
      averageLifespan: null,
      eyeColors: ["black"],
      hairColors: [],
      skinColors: ["grey", "yellow", "purple"],
      language: "Xextese",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoxOQ==",
      name: "Toong",
      classification: "unknown",
      designation: "sentient",
      averageHeight: 200,
      averageLifespan: null,
      eyeColors: ["orange"],
      hairColors: [],
      skinColors: ["grey", "green", "yellow"],
      language: "Tundan",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyMA==",
      name: "Cerean",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 200,
      averageLifespan: null,
      eyeColors: ["hazel"],
      hairColors: ["red", "blond", "black", "white"],
      skinColors: ["pale pink"],
      language: "Cerean",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyMQ==",
      name: "Nautolan",
      classification: "amphibian",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: 70,
      eyeColors: ["black"],
      hairColors: [],
      skinColors: ["green", "blue", "brown", "red"],
      language: "Nautila",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyMg==",
      name: "Zabrak",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: null,
      eyeColors: ["brown", "orange"],
      hairColors: ["black"],
      skinColors: ["pale", "brown", "red", "orange", "yellow"],
      language: "Zabraki",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyMw==",
      name: "Tholothian",
      classification: "mammal",
      designation: "sentient",
      averageHeight: null,
      averageLifespan: null,
      eyeColors: ["blue", "indigo"],
      hairColors: ["unknown"],
      skinColors: ["dark"],
      language: "unknown",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyNA==",
      name: "Iktotchi",
      classification: "unknown",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: null,
      eyeColors: ["orange"],
      hairColors: [],
      skinColors: ["pink"],
      language: "Iktotchese",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyNQ==",
      name: "Quermian",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 240,
      averageLifespan: 86,
      eyeColors: ["yellow"],
      hairColors: [],
      skinColors: ["white"],
      language: "Quermian",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyNg==",
      name: "Kel Dor",
      classification: "unknown",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: 70,
      eyeColors: ["black", "silver"],
      hairColors: [],
      skinColors: ["peach", "orange", "red"],
      language: "Kel Dor",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyNw==",
      name: "Chagrian",
      classification: "amphibian",
      designation: "sentient",
      averageHeight: 190,
      averageLifespan: null,
      eyeColors: ["blue"],
      hairColors: [],
      skinColors: ["blue"],
      language: "Chagria",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyOA==",
      name: "Geonosian",
      classification: "insectoid",
      designation: "sentient",
      averageHeight: 178,
      averageLifespan: null,
      eyeColors: ["green", "hazel"],
      hairColors: [],
      skinColors: ["green", "brown"],
      language: "Geonosian",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczoyOQ==",
      name: "Mirialan",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: null,
      eyeColors: ["blue", "green", "red", "yellow", "brown", "orange"],
      hairColors: ["black", "brown"],
      skinColors: ["yellow", "green"],
      language: "Mirialan",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozMA==",
      name: "Clawdite",
      classification: "reptilian",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: 70,
      eyeColors: ["yellow"],
      hairColors: [],
      skinColors: ["green", "yellow"],
      language: "Clawdite",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozMQ==",
      name: "Besalisk",
      classification: "amphibian",
      designation: "sentient",
      averageHeight: 178,
      averageLifespan: 75,
      eyeColors: ["yellow"],
      hairColors: [],
      skinColors: ["brown"],
      language: "besalisk",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozMg==",
      name: "Kaminoan",
      classification: "amphibian",
      designation: "sentient",
      averageHeight: 220,
      averageLifespan: 80,
      eyeColors: ["black"],
      hairColors: [],
      skinColors: ["grey", "blue"],
      language: "Kaminoan",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozMw==",
      name: "Skakoan",
      classification: "mammal",
      designation: "sentient",
      averageHeight: null,
      averageLifespan: null,
      eyeColors: ["unknown"],
      hairColors: [],
      skinColors: ["grey", "green"],
      language: "Skakoan",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozNA==",
      name: "Muun",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 190,
      averageLifespan: 100,
      eyeColors: ["black"],
      hairColors: [],
      skinColors: ["grey", "white"],
      language: "Muun",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozNQ==",
      name: "Togruta",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 180,
      averageLifespan: 94,
      eyeColors: ["red", "orange", "yellow", "green", "blue", "black"],
      hairColors: [],
      skinColors: ["red", "white", "orange", "yellow", "green", "blue"],
      language: "Togruti",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozNg==",
      name: "Kaleesh",
      classification: "reptile",
      designation: "sentient",
      averageHeight: 170,
      averageLifespan: 80,
      eyeColors: ["yellow"],
      hairColors: [],
      skinColors: ["brown", "orange", "tan"],
      language: "Kaleesh",
    },
    {
      __typename: "Species",
      id: "c3BlY2llczozNw==",
      name: "Pau'an",
      classification: "mammal",
      designation: "sentient",
      averageHeight: 190,
      averageLifespan: 700,
      eyeColors: ["black"],
      hairColors: [],
      skinColors: ["grey"],
      language: "Utapese",
    },
  ],
  totalCount: 37,
  title: "Species",
};
